version: 2.1

executors:
  default:
    docker:
      - image: quay.io/hemanth22/rockylinux9:9

jobs:
  build:
    executor: default
    steps:
      - checkout
      - run:
          name: Print Python Verson
          command: |
            dnf install python3-pip -y
            python3 -V
            python3 -m pip install requests nsepython
      - run:
          name: ETF Most Active Volume
          command: |
            python3 mostactiveetfvol.py

      - run:
          name: Wait for 5 seconds
          command: |
            python3 -c "import time; time.sleep(5)"

      - run:
          name: Stock Most Active Volume
          command: |
            python3 mostactivestocks.py

workflows:
  notify_app:
    jobs:
      - build
    triggers:
      - schedule:
          cron: "45 9 * * *"
          filters:
            branches:
              only:
                - main
